//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://tempuri.org/", ClrNamespace="tempuri.org")]

namespace tempuri.org
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenPayServiceRequest", Namespace="http://tempuri.org/")]
    public partial class TokenPayServiceRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private tempuri.org.TokenCardAuthRequest MERCHANTField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public tempuri.org.TokenCardAuthRequest MERCHANT
        {
            get
            {
                return this.MERCHANTField;
            }
            set
            {
                this.MERCHANTField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenCardAuthRequest", Namespace="http://tempuri.org/")]
    public partial class TokenCardAuthRequest : tempuri.org.OrderAuthBasic
    {
        
        private tempuri.org.TokenPayAuthInfoMerchant AUTHORDERINFOField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public tempuri.org.TokenPayAuthInfoMerchant AUTHORDERINFO
        {
            get
            {
                return this.AUTHORDERINFOField;
            }
            set
            {
                this.AUTHORDERINFOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderAuthBasic", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(tempuri.org.TokenCardAuthResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(tempuri.org.TokenCardAuthRequest))]
    public partial class OrderAuthBasic : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private tempuri.org.AUTHMSGID MSGIDField;
        
        private string CAVALUEField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public tempuri.org.AUTHMSGID MSGID
        {
            get
            {
                return this.MSGIDField;
            }
            set
            {
                this.MSGIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CAVALUE
        {
            get
            {
                return this.CAVALUEField;
            }
            set
            {
                this.CAVALUEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenCardAuthResponse", Namespace="http://tempuri.org/")]
    public partial class TokenCardAuthResponse : tempuri.org.OrderAuthBasic
    {
        
        private tempuri.org.TokenPaymentType PAYMENTTYPEField;
        
        private tempuri.org.TokenPayAuthInfoCUB AUTHORDERINFOField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public tempuri.org.TokenPaymentType PAYMENTTYPE
        {
            get
            {
                return this.PAYMENTTYPEField;
            }
            set
            {
                this.PAYMENTTYPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public tempuri.org.TokenPayAuthInfoCUB AUTHORDERINFO
        {
            get
            {
                return this.AUTHORDERINFOField;
            }
            set
            {
                this.AUTHORDERINFOField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AUTHMSGID", Namespace="http://tempuri.org/")]
    public enum AUTHMSGID : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRS0001 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRS0002 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRS0003 = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenPayAuthInfoMerchant", Namespace="http://tempuri.org/")]
    public partial class TokenPayAuthInfoMerchant : tempuri.org.MerchantAuthInfo
    {
        
        private string PAYINField;
        
        private string PAYMENTDATAField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PAYIN
        {
            get
            {
                return this.PAYINField;
            }
            set
            {
                this.PAYINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PAYMENTDATA
        {
            get
            {
                return this.PAYMENTDATAField;
            }
            set
            {
                this.PAYMENTDATAField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenPayAuthInfoCUB", Namespace="http://tempuri.org/")]
    public partial class TokenPayAuthInfoCUB : tempuri.org.CUBAuthInfo
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenPaymentType", Namespace="http://tempuri.org/")]
    public enum TokenPaymentType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Others = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Apple = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Google = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Samsung = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CUBAuthInfo", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(tempuri.org.TokenPayAuthInfoCUB))]
    public partial class CUBAuthInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string STOREIDField;
        
        private string ORDERNUMBERField;
        
        private string AMOUNTField;
        
        private int PERIODNUMBERField;
        
        private tempuri.org.Redeem REDEEMField;
        
        private string AUTHSTATUSField;
        
        private string AUTHCODEField;
        
        private string AUTHTIMEField;
        
        private string AUTHMSGField;
        
        private int REDEEMPOINTField;
        
        private int REDEEMAMOUNTField;
        
        private int PAIDAMOUNTField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string STOREID
        {
            get
            {
                return this.STOREIDField;
            }
            set
            {
                this.STOREIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ORDERNUMBER
        {
            get
            {
                return this.ORDERNUMBERField;
            }
            set
            {
                this.ORDERNUMBERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AMOUNT
        {
            get
            {
                return this.AMOUNTField;
            }
            set
            {
                this.AMOUNTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int PERIODNUMBER
        {
            get
            {
                return this.PERIODNUMBERField;
            }
            set
            {
                this.PERIODNUMBERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public tempuri.org.Redeem REDEEM
        {
            get
            {
                return this.REDEEMField;
            }
            set
            {
                this.REDEEMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AUTHSTATUS
        {
            get
            {
                return this.AUTHSTATUSField;
            }
            set
            {
                this.AUTHSTATUSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AUTHCODE
        {
            get
            {
                return this.AUTHCODEField;
            }
            set
            {
                this.AUTHCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AUTHTIME
        {
            get
            {
                return this.AUTHTIMEField;
            }
            set
            {
                this.AUTHTIMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AUTHMSG
        {
            get
            {
                return this.AUTHMSGField;
            }
            set
            {
                this.AUTHMSGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int REDEEMPOINT
        {
            get
            {
                return this.REDEEMPOINTField;
            }
            set
            {
                this.REDEEMPOINTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int REDEEMAMOUNT
        {
            get
            {
                return this.REDEEMAMOUNTField;
            }
            set
            {
                this.REDEEMAMOUNTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int PAIDAMOUNT
        {
            get
            {
                return this.PAIDAMOUNTField;
            }
            set
            {
                this.PAIDAMOUNTField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Redeem", Namespace="http://tempuri.org/")]
    public enum Redeem : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PART = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MerchantAuthInfo", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(tempuri.org.TokenPayAuthInfoMerchant))]
    public partial class MerchantAuthInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string STOREIDField;
        
        private string ORDERNUMBERField;
        
        private string AMOUNTField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string STOREID
        {
            get
            {
                return this.STOREIDField;
            }
            set
            {
                this.STOREIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ORDERNUMBER
        {
            get
            {
                return this.ORDERNUMBERField;
            }
            set
            {
                this.ORDERNUMBERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AMOUNT
        {
            get
            {
                return this.AMOUNTField;
            }
            set
            {
                this.AMOUNTField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenPayServiceResponse", Namespace="http://tempuri.org/")]
    public partial class TokenPayServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private tempuri.org.TokenCardAuthResponse CUBField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public tempuri.org.TokenCardAuthResponse CUB
        {
            get
            {
                return this.CUBField;
            }
            set
            {
                this.CUBField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITokenPayService")]
public interface ITokenPayService
{
    
    // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  objTokenCardAuthRequest 未標示為 nillable，正在產生訊息合約
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenPayService/TokenPay", ReplyAction="http://tempuri.org/ITokenPayService/TokenPayResponse")]
    TokenPayResponse TokenPay(TokenPayRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenPayService/TokenPay", ReplyAction="http://tempuri.org/ITokenPayService/TokenPayResponse")]
    System.Threading.Tasks.Task<TokenPayResponse> TokenPayAsync(TokenPayRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class TokenPayRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="TokenPay", Namespace="http://tempuri.org/", Order=0)]
    public TokenPayRequestBody Body;
    
    public TokenPayRequest()
    {
    }
    
    public TokenPayRequest(TokenPayRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class TokenPayRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.TokenPayServiceRequest objTokenCardAuthRequest;
    
    public TokenPayRequestBody()
    {
    }
    
    public TokenPayRequestBody(tempuri.org.TokenPayServiceRequest objTokenCardAuthRequest)
    {
        this.objTokenCardAuthRequest = objTokenCardAuthRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class TokenPayResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="TokenPayResponse", Namespace="http://tempuri.org/", Order=0)]
    public TokenPayResponseBody Body;
    
    public TokenPayResponse()
    {
    }
    
    public TokenPayResponse(TokenPayResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class TokenPayResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.TokenPayServiceResponse TokenPayResult;
    
    public TokenPayResponseBody()
    {
    }
    
    public TokenPayResponseBody(tempuri.org.TokenPayServiceResponse TokenPayResult)
    {
        this.TokenPayResult = TokenPayResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITokenPayServiceChannel : ITokenPayService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TokenPayServiceClient : System.ServiceModel.ClientBase<ITokenPayService>, ITokenPayService
{
    
    public TokenPayServiceClient()
    {
    }
    
    public TokenPayServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TokenPayServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TokenPayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TokenPayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TokenPayResponse ITokenPayService.TokenPay(TokenPayRequest request)
    {
        return base.Channel.TokenPay(request);
    }
    
    public tempuri.org.TokenPayServiceResponse TokenPay(tempuri.org.TokenPayServiceRequest objTokenCardAuthRequest)
    {
        TokenPayRequest inValue = new TokenPayRequest();
        inValue.Body = new TokenPayRequestBody();
        inValue.Body.objTokenCardAuthRequest = objTokenCardAuthRequest;
        TokenPayResponse retVal = ((ITokenPayService)(this)).TokenPay(inValue);
        return retVal.Body.TokenPayResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<TokenPayResponse> ITokenPayService.TokenPayAsync(TokenPayRequest request)
    {
        return base.Channel.TokenPayAsync(request);
    }
    
    public System.Threading.Tasks.Task<TokenPayResponse> TokenPayAsync(tempuri.org.TokenPayServiceRequest objTokenCardAuthRequest)
    {
        TokenPayRequest inValue = new TokenPayRequest();
        inValue.Body = new TokenPayRequestBody();
        inValue.Body.objTokenCardAuthRequest = objTokenCardAuthRequest;
        return ((ITokenPayService)(this)).TokenPayAsync(inValue);
    }
}
